NODE_RADIUS = 30
BACKGROUND_COLOR = "black"
NODE_COLOR = "white"
HIGHLIGHT_COLOR = "red"
HIGHLIGHT_TEXT_COLOR = "white"
TEXT_COLOR = "black"
LINE_COLOR = "white"
FONT_SIZE = 20

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700

X_PADDING = 150

Y_PADDING = NODE_RADIUS * 4 + 5

MAX_DEPTH = 4
MAX_VALUE = 100
MIN_VALUE = 0

ANIMATION_DELAY = 1
