NODE_RADIUS = 25
BACKGROUND_COLOR = "black"
NODE_COLOR = "white"
HIGHLIGHT_COLOR = "red"
HIGHLIGHT_TEXT_COLOR = "white"
TEXT_COLOR = "black"
LINE_COLOR = "white"
FONT_SIZE = 15

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
X_PADDING = 150
Y_PADDING = NODE_RADIUS * 4

MAX_DEPTH = 4
MIN_VALUE = 0
MAX_VALUE = 100

ANIMATION_DELAY = 0.2
